//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProjectInstitute.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormationGroup
    {
        public int IDFormation { get; set; }
        public int IDGroup { get; set; }
        public Nullable<System.DateTime> Datedebut { get; set; }
        public Nullable<System.DateTime> DateFin { get; set; }
    
        public virtual Formation Formation { get; set; }
        public virtual Groupe Groupe { get; set; }
    }
}
