//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProjectInstitute.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historique
    {
        public int IdAction { get; set; }
        public string Action { get; set; }
        public Nullable<System.DateTime> dateAction { get; set; }
        public Nullable<int> IdUtilisateur { get; set; }
    
        public virtual Utilisateur Utilisateur { get; set; }
    }
}
