//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProjectInstitute.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EducationInstitute : DbContext
    {
        public EducationInstitute()
            : base("name=EducationInstitute")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AbsenceEtudient> AbsenceEtudients { get; set; }
        public virtual DbSet<AbsenceProfesseur> AbsenceProfesseurs { get; set; }
        public virtual DbSet<Etudient> Etudients { get; set; }
        public virtual DbSet<EtudientGroupe> EtudientGroupes { get; set; }
        public virtual DbSet<Formation> Formations { get; set; }
        public virtual DbSet<FormationGroup> FormationGroups { get; set; }
        public virtual DbSet<Groupe> Groupes { get; set; }
        public virtual DbSet<Historique> Historiques { get; set; }
        public virtual DbSet<PieceEtudient> PieceEtudients { get; set; }
        public virtual DbSet<PieceProfesseur> PieceProfesseurs { get; set; }
        public virtual DbSet<Professeur> Professeurs { get; set; }
        public virtual DbSet<ProfesseurFormation> ProfesseurFormations { get; set; }
        public virtual DbSet<ProfesseurGroupe> ProfesseurGroupes { get; set; }
        public virtual DbSet<Seance> Seances { get; set; }
        public virtual DbSet<Utilisateur> Utilisateurs { get; set; }
    }
}
