//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProjectInstitute.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Professeur
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Professeur()
        {
            this.AbsenceProfesseurs = new HashSet<AbsenceProfesseur>();
            this.PieceProfesseurs = new HashSet<PieceProfesseur>();
            this.ProfesseurFormations = new HashSet<ProfesseurFormation>();
            this.ProfesseurGroupes = new HashSet<ProfesseurGroupe>();
            this.Seances = new HashSet<Seance>();
        }
    
        public int IdProf { get; set; }
        public string CIN { get; set; }
        public string Email { get; set; }
        public string Adresse { get; set; }
        public string Telephone { get; set; }
        public string NomComplet { get; set; }
        public string Sexe { get; set; }
        public Nullable<System.DateTime> DateNaissance { get; set; }
        public Nullable<int> age { get; set; }
        public Nullable<double> Salaire { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AbsenceProfesseur> AbsenceProfesseurs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PieceProfesseur> PieceProfesseurs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfesseurFormation> ProfesseurFormations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfesseurGroupe> ProfesseurGroupes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seance> Seances { get; set; }
    }
}
